### ISSUE TITLE
Design - Projekt målepunkter

### ISSUE THREAD

**Issue by KasperHenningsen** [KarmaKamikaze/ChatRPG#16]

**Comment by damniko** [comment]
Fx. antal features i vores vs. andre relaterede systemer.

**Comment by damniko** [comment]
@Sarmisuper @KarmaKamikaze @selectionator @mirakst Det her er klar til review. Metrics er gjort mere concise og er flyttet ud i tabeller (det har I allerede kigget på). Nu er brødteksten i afsnittet også færdig, så det går i dybden med indholdet af tabellerne - hvordan det måles, hvorfor det er relevant, etc.
Plz Review!

**Comment by KarmaKamikaze** [comment]
@damniko Afsnittet er mega lækkert og brødteksten fungerer godt sammen med dine tables!
Jeg har lagt et par enkelte suggestions som kommentare, men du kan resolve dem, hvis ikke du er enige i at der er nogen fordele ved at inkludere dem. Det eneste jeg undrede mig over, som muligvis behøver en fremgangsmåde, er hvordan vi automatisk tester Accuracy og Conformity.

**Comment by KarmaKamikaze** [comment]
Hov, og lige en sidste ting! Jeg synes ikke vi skal give hver metric et id. Det virker lidt underligt, når de har korte navne, som er meget sigende ift. deres måleområde. Så hvis man vil referere til en metric synes jeg det ville være lettere at læse navnet frem for et id, da man ville skulle finde tabellen for at finde ud af hvad det betyder.

**Comment by selectionator** [comment]
Har også sat et par kommentarer :+1:
