### ISSUE TITLE
Testing - Design usability test

### ISSUE THREAD

**Issue by KasperHenningsen** [KarmaKamikaze/ChatRPG#17]

**Comment by selectionator** [comment]
En introducerende tekst er skrevet til vores usability testing framework. Vi mangler at anvende denne til at lave den egentlige usability test, som vi først kan gøre når vi har implementeret designet 😊

**Comment by selectionator** [comment]
Har lavet et skelet til den egentlige usability test, som skal ændres lidt, når vi nærmer os testing
