### ISSUE TITLE
Design - UI

### ISSUE THREAD

**Issue by Sarmisuper** [KarmaKamikaze/ChatRPG#2]

**Comment by KasperHenningsen** [comment]
https://www.figma.com/file/4bNoER89o6ccaVvMpYYOUy/P7-UI-sketch?type=design&node-id=0%3A1&mode=design&t=3QYU5gNydGAtJ4Qg-1

**Comment by Sarmisuper** [comment]
@damniko Jeg har kigget på dine comments og også skrevet en introduktion. Kan du lige rereview?
