### ISSUE TITLE
Problemanalyse Introduktion

### ISSUE THREAD

**Issue by Sarmisuper** [KarmaKamikaze/ChatRPG#24]

**Comment by Sarmisuper** [comment]
Har prøvet at skrive det uden at gå i detajlerne, men kan være at rapport-rotten sammen med sanwe-rotten har consumed min hjerne.

**Comment by selectionator** [comment]
LGTM 👍

**Comment by KarmaKamikaze** [comment]
Yep, seems fine. Rotten får lov at leve en dag endnu.
