### ISSUE TITLE
Feature - Game Controller

### ISSUE THREAD

**Issue by KarmaKamikaze** [KarmaKamikaze/ChatRPG#33]

**Comment by damniko** [comment]
REVIEWS PL0XII

**Comment by damniko** [comment]
FACK NEVERMIND

**Comment by mirakst** [comment]
It should be possible to get the opening and closing symbols of the assistants output to the player, such that the campaign page can use these to filter what is shown to the player.

**Comment by damniko** [comment]
hmm, yes, mhmm, ... yes, I know some of these words

**Comment by mirakst** [comment]
> hmm, yes, mhmm, ... yes, I know some of these words

Idéen er at vi skal kunne vise kun det relevante for spilleren i UI, e.g. for output: 
"Context start
asdfasfkoasfk
Context end

Events start
asopkfopok
Events end

Response start
You walk up to the burly bearded dwarf and notice that he has a fat pouch strung to his belt.
Repsonse end"

UI (player view) viser:
"You walk up to the burly bearded dwarf and notice that he has a fat pouch strung to his belt."

Controlleren skal læse det hele, og skal kunne fortælle UI hvordan det skal filtrere på beskeden, e.g. med regex. Controlleren skal kunne parse de forskellige sektioner, og den måde vi strukturerer disse sektioner er subject to change, så vi vil gerne kunne ændre det ét sted og så kommunikere til UI hvordan det skal filtrere output (e.g. metode GetResponseRegex)
