### ISSUE TITLE
Design - Data Model and Persistence

### ISSUE THREAD

**Issue by Sarmisuper** [KarmaKamikaze/ChatRPG#7]
[Link til design (draw.io)](https://drive.google.com/file/d/1BHmGyvY7oX_z-rTmXu1X6uVdO2mzcgl5/view?usp=sharing)

**Comment by damniko** [comment]
[Link til design (draw.io)](https://drive.google.com/file/d/1BHmGyvY7oX_z-rTmXu1X6uVdO2mzcgl5/view?usp=sharing)

**Comment by damniko** [comment]
Sektion "Data Model and Persistence", til (men ikke med) undersektionen om ERD. Jeg forventer at diagrammet ikke er helt færdigt, og tænker godt vi kan vente lidt med at beskrive den i detaljer.

**Comment by KasperHenningsen** [comment]
Updater ERD med conversation.
Brugerens input og LLM response skal gemmes, så brugeren har en historik i UI at scrolle igennem.

**Comment by damniko** [comment]
@Sarmisuper Jeg har rettet hele afsnittet til i rapporten. Vil du kigge det igennem igen ved lejlighed?

**Comment by Sarmisuper** [comment]
@damniko Nej

**Comment by Sarmisuper** [comment]
@damniko AAARRRRG JK JK, jeg skal nok kigge på det. Men kun hvis du så genreviewe UI ved lejlighed

**Comment by Sarmisuper** [comment]
@damniko Nu har jeg fået kigget på det min ven

**Comment by damniko** [comment]
TFW @Sarmisuper skriver kommentarer til dit afsnit med mere indhold end selve afsnittet: 

![Image](https://github.com/KarmaKamikaze/ChatRPG/assets/71791903/0a0a6d9f-3987-44c2-84ab-fd4519bb92d4)

**Comment by Sarmisuper** [comment]
@damniko Ja det blev sku til lidt mange, sry. Vi kan lige kigge på dem sammen imorgen 🥰
