### ISSUE TITLE
Findings - Performance metrics / Quantitative metrics

### ISSUE THREAD

**Issue by Sarmisuper** [KarmaKamikaze/ChatRPG#89]

**Comment by damniko** [comment]
@Sarmisuper @KasperHenningsen @selectionator pls review

**Comment by damniko** [comment]
jeg mente @KarmaKamikaze sry @KasperHenningsen

**Comment by Sarmisuper** [comment]
Har reviewed

**Comment by damniko** [comment]
@Sarmisuper fuck så skal jeg lave noget igen
